### ISSUE TITLE
Custom wallpapers

### ISSUE THREAD

**Issue by opuadm** [blueedgetechno/win11React#348]
I want personalization colors category to be added here. there should be change colors. dark and white mode. and add background changer. add custom and windows 11 wallpapers. but add custom bakcground apply option. Then thanks.

**Comment by yashash1511** [comment]
![image](https://user-images.githubusercontent.com/89068816/158303632-d7b80610-a09c-4ffe-9a26-0bf97e2b9fbb.png)
for switching between light and dark mode we already have this toggle in action centre

For custom wallpapers thats something we can look into

![image](https://user-images.githubusercontent.com/89068816/158303796-234e7664-15a8-41e5-9422-45888f58cedc.png)
for windows 11 default wallpapers we already have them (check settings -> personalisation)

**Comment by opuadm** [comment]
> > dark and white mode
> 
> ![image](https://user-images.githubusercontent.com/89068816/158304340-600109ab-7661-4109-bc6a-09db83a0bfc4.png)
> for switching between light and dark mode we already have the theme toggle in action centre
> 
> 
> > windows 11 wallpapers
> 
> ![image](https://user-images.githubusercontent.com/89068816/158304477-591fc1a5-c98e-4c62-96af-2554a257d67e.png)
> we already have them, check settings -> personalisation
> 
> 
> > add custom bakcground apply option
> 
> thats something we can look into
> 
> Not sure what do mean by Colors Personalization

Oh i forgot that there's dark and light toggle

**Comment by zeronegithub** [comment]
Add custom background apply option with image url
ex: https://i.imgur.com/dfij3ek.jpeg
