### ISSUE TITLE
[Bug]: Most windows apps

### ISSUE THREAD

**Issue by Andrew3123** [blueedgetechno/win11React#370]
### What happened?

Where has the Settings app gone? Where is the Microsoft Store? Where is the File Explorer??????

When clicking those apps it just sends you to the rickroll page.

PLEASE BLUEEDGE FIX THIS!!!!!!!!!!!!!!!!!!!

### To reproduce the behavior?

First step: Remove the Rickrolls.

2nd step: ReAdd the apps that are missing.

3rd step: Remove the BSOD.

### What browser are you seeing the problem on?

Microsoft Edge

**Comment by MalikIdreesHasanKhan** [comment]
It's april fools day

**Comment by andrewstech** [comment]
Fixed
