### ISSUE TITLE
The option to change username and profile picture

### ISSUE THREAD

**Issue by blgoreuxe** [blueedgetechno/win11React#424]
I think that it will be a really cool feature in the settings app to change the username to a custom choice instead of just Blue Edge, and then a custom profile picture from a url or from your local files.

**Comment by glitch128** [comment]
yes. please do this

**Comment by zero90002** [comment]
heck
ye

**Comment by yashash1511** [comment]
Duplicate of #374

**Comment by yashash1511** [comment]
Duplicate of #301
