### ISSUE TITLE
[Bug] In settings, clicking accounts leads to BSOD

### ISSUE THREAD

**Issue by markandpreston123** [blueedgetechno/win11React#491]
### What happened?

In the Settings Apps, clicking on Accounts leads to a BSOD with stop code: O2 is undefined.

### To reproduce the behavior?

1) Go to Settings
2) Click Accounts.
there.

### What browser are you seeing the problem on?

Firefox

**Comment by yashash1511** [comment]
works fine on edge (chromium)

https://user-images.githubusercontent.com/89068816/171240289-14d5ce84-9994-4e12-891f-ea7f5ee4cb78.mp4

**Comment by notAperson535** [comment]
> works fine on edge (chromium)

@yashash1511 Nice! Another edge user!

**Comment by yashash1511** [comment]
@markandpreston123 we are unable to repro this can you share something like a screenrecording

**Comment by notAperson535** [comment]
I saw this too but it only happened once on one of my computers. Try clearing the cache and cookies to "update"

**Comment by yashash1511** [comment]
can't repro
