### ISSUE TITLE
Let's improve the items in Search tab

### ISSUE THREAD

**Issue by chiaramistro** [blueedgetechno/win11React#664]
**Is your feature request related to a problem? Please describe.**
When I enter in the Search tab, I see all the items on Top Apps. When I click on an item, the click works only if I click on the image (but not on the item itself, for example in the grey background).

**Describe the solution you'd like**
I would like to be able to click on the item instead of the image.

**Describe alternatives you've considered**
No alternatives considered.

**Additional context**
![image](https://user-images.githubusercontent.com/41189322/193863382-3921b69e-6771-4a04-9c2d-50f7cad9694e.png)

**Comment by chiaramistro** [comment]
I would like to work on this enhancement :)

**Comment by yashash1511** [comment]
go ahead :) @chiaramistro

**Comment by chiaramistro** [comment]
Hello everyone. It is not clear to me why my contribution was not accepted and the issue has been closed. 
The issue seems to have been resolved in pull request #672 which has the same code I wrote in my pull request #665. I am asking for feedback to know if I did something wrong in case I make future contributions.
Thanks :)

**Comment by andrewstech** [comment]
> Hello everyone. It is not clear to me why my contribution was not accepted and the issue has been closed. The issue seems to have been resolved in pull request #672 which has the same code I wrote in my pull request #665. I am asking for feedback to know if I did something wrong in case I make future contributions. Thanks :)

I'm not sure ether. I've given you the HACKTOBERFEST-ACCEPTED label so your contribution will count towards your goal

**Comment by chiaramistro** [comment]
> > Hello everyone. It is not clear to me why my contribution was not accepted and the issue has been closed. The issue seems to have been resolved in pull request #672 which has the same code I wrote in my pull request #665. I am asking for feedback to know if I did something wrong in case I make future contributions. Thanks :)
> 
> I'm not sure ether. I've given you the HACKTOBERFEST-ACCEPTED label so your contribution will count towards your goal

Oh okay, I’m glad you explained. Thank you for your feedback!
