### ISSUE TITLE
[Bug]: Site always redirects 

### ISSUE THREAD

**Issue by Riftriot** [blueedgetechno/win11React#760]
### What happened?

When I build win11React with vite and serve the build dir using a nodejs script, it always redirects to https://andrewstech.me/win11react-add-test/, and i would like to host it locally rather than having it redirect.

### To reproduce the behavior?

Build and put the build dir in the same dir as this nodejs script:

`const express = require('express');
const path = require('path');

const app = express();

app.use(express.static(path.join(__dirname, 'build')));

app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, 'build', 'index.html'));
});

app.listen(3000, () => {
  console.log('Server is listening on port 3000');
});
`

### What browser are you seeing the problem on?

Chrome

**Comment by andrewstech** [comment]
This is only a temporary thing for our main site. You can disable it by removing line 6 from this file https://github.com/blueedgetechno/win11React/blob/master/public/react-pwa.js

**Comment by Riftriot** [comment]
Thank you
